import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";
import { ReactQueryProvider } from "./Providers/ReacrQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Toaster } from "react-hot-toast";
import AccessProvider from "./Providers/CaslProvider";
import { AuthProvider } from "./hooks/useAuth";
import { MessageToaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <AuthProvider>
        <html lang="en">
          <body className={`${inter.className} scrollbar-none overflow-hidden`}>
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
            <Toaster />
            <MessageToaster />
          </body>
        </html>
      </AuthProvider>
    </ReactQueryProvider>
  );
}
